generator:
  class: sfPropelGenerator
  param:
    model_class:           Parametro
    theme:                 admin15
    non_verbose_templates: true
    with_show:             false
    singular:              Parametro
    plural:                Parametros
    route_prefix:          parametro
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
          display:         [descripcion, valor]
      filter:
          display:         [descripcion]
      form:
          display:         [descripcion, valor]
      edit:    ~
      new:     ~
