<?php


/**
 * Base class that represents a query for the 'archivo_calificacion' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * Thu Feb 23 06:33:16 2017
 *
 * @method ArchivoCalificacionQuery orderById($order = Criteria::ASC) Order by the id column
 * @method ArchivoCalificacionQuery orderByArchivoId($order = Criteria::ASC) Order by the archivo_id column
 * @method ArchivoCalificacionQuery orderByUsuarioId($order = Criteria::ASC) Order by the usuario_id column
 * @method ArchivoCalificacionQuery orderByPunteo($order = Criteria::ASC) Order by the punteo column
 *
 * @method ArchivoCalificacionQuery groupById() Group by the id column
 * @method ArchivoCalificacionQuery groupByArchivoId() Group by the archivo_id column
 * @method ArchivoCalificacionQuery groupByUsuarioId() Group by the usuario_id column
 * @method ArchivoCalificacionQuery groupByPunteo() Group by the punteo column
 *
 * @method ArchivoCalificacionQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method ArchivoCalificacionQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method ArchivoCalificacionQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method ArchivoCalificacionQuery leftJoinArchivo($relationAlias = null) Adds a LEFT JOIN clause to the query using the Archivo relation
 * @method ArchivoCalificacionQuery rightJoinArchivo($relationAlias = null) Adds a RIGHT JOIN clause to the query using the Archivo relation
 * @method ArchivoCalificacionQuery innerJoinArchivo($relationAlias = null) Adds a INNER JOIN clause to the query using the Archivo relation
 *
 * @method ArchivoCalificacionQuery leftJoinUsuario($relationAlias = null) Adds a LEFT JOIN clause to the query using the Usuario relation
 * @method ArchivoCalificacionQuery rightJoinUsuario($relationAlias = null) Adds a RIGHT JOIN clause to the query using the Usuario relation
 * @method ArchivoCalificacionQuery innerJoinUsuario($relationAlias = null) Adds a INNER JOIN clause to the query using the Usuario relation
 *
 * @method ArchivoCalificacion findOne(PropelPDO $con = null) Return the first ArchivoCalificacion matching the query
 * @method ArchivoCalificacion findOneOrCreate(PropelPDO $con = null) Return the first ArchivoCalificacion matching the query, or a new ArchivoCalificacion object populated from the query conditions when no match is found
 *
 * @method ArchivoCalificacion findOneById(int $id) Return the first ArchivoCalificacion filtered by the id column
 * @method ArchivoCalificacion findOneByArchivoId(int $archivo_id) Return the first ArchivoCalificacion filtered by the archivo_id column
 * @method ArchivoCalificacion findOneByUsuarioId(int $usuario_id) Return the first ArchivoCalificacion filtered by the usuario_id column
 * @method ArchivoCalificacion findOneByPunteo(int $punteo) Return the first ArchivoCalificacion filtered by the punteo column
 *
 * @method array findById(int $id) Return ArchivoCalificacion objects filtered by the id column
 * @method array findByArchivoId(int $archivo_id) Return ArchivoCalificacion objects filtered by the archivo_id column
 * @method array findByUsuarioId(int $usuario_id) Return ArchivoCalificacion objects filtered by the usuario_id column
 * @method array findByPunteo(int $punteo) Return ArchivoCalificacion objects filtered by the punteo column
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseArchivoCalificacionQuery extends ModelCriteria
{
    /**
     * Initializes internal state of BaseArchivoCalificacionQuery object.
     *
     * @param     string $dbName The dabase name
     * @param     string $modelName The phpName of a model, e.g. 'Book'
     * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
     */
    public function __construct($dbName = 'propel', $modelName = 'ArchivoCalificacion', $modelAlias = null)
    {
        parent::__construct($dbName, $modelName, $modelAlias);
    }

    /**
     * Returns a new ArchivoCalificacionQuery object.
     *
     * @param     string $modelAlias The alias of a model in the query
     * @param     ArchivoCalificacionQuery|Criteria $criteria Optional Criteria to build the query from
     *
     * @return ArchivoCalificacionQuery
     */
    public static function create($modelAlias = null, $criteria = null)
    {
        if ($criteria instanceof ArchivoCalificacionQuery) {
            return $criteria;
        }
        $query = new ArchivoCalificacionQuery();
        if (null !== $modelAlias) {
            $query->setModelAlias($modelAlias);
        }
        if ($criteria instanceof Criteria) {
            $query->mergeWith($criteria);
        }

        return $query;
    }

    /**
     * Find object by primary key.
     * Propel uses the instance pool to skip the database if the object exists.
     * Go fast if the query is untouched.
     *
     * <code>
     * $obj  = $c->findPk(12, $con);
     * </code>
     *
     * @param mixed $key Primary key to use for the query
     * @param     PropelPDO $con an optional connection object
     *
     * @return   ArchivoCalificacion|ArchivoCalificacion[]|mixed the result, formatted by the current formatter
     */
    public function findPk($key, $con = null)
    {
        if ($key === null) {
            return null;
        }
        if ((null !== ($obj = ArchivoCalificacionPeer::getInstanceFromPool((string) $key))) && !$this->formatter) {
            // the object is alredy in the instance pool
            return $obj;
        }
        if ($con === null) {
            $con = Propel::getConnection(ArchivoCalificacionPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        if ($this->formatter || $this->modelAlias || $this->with || $this->select
         || $this->selectColumns || $this->asColumns || $this->selectModifiers
         || $this->map || $this->having || $this->joins) {
            return $this->findPkComplex($key, $con);
        } else {
            return $this->findPkSimple($key, $con);
        }
    }

    /**
     * Find object by primary key using raw SQL to go fast.
     * Bypass doSelect() and the object formatter by using generated code.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return   ArchivoCalificacion A model object, or null if the key is not found
     * @throws   PropelException
     */
    protected function findPkSimple($key, $con)
    {
        $sql = 'SELECT `ID`, `ARCHIVO_ID`, `USUARIO_ID`, `PUNTEO` FROM `archivo_calificacion` WHERE `ID` = :p0';
        try {
            $stmt = $con->prepare($sql);
            $stmt->bindValue(':p0', $key, PDO::PARAM_INT);
            $stmt->execute();
        } catch (Exception $e) {
            Propel::log($e->getMessage(), Propel::LOG_ERR);
            throw new PropelException(sprintf('Unable to execute SELECT statement [%s]', $sql), $e);
        }
        $obj = null;
        if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $obj = new ArchivoCalificacion();
            $obj->hydrate($row);
            ArchivoCalificacionPeer::addInstanceToPool($obj, (string) $key);
        }
        $stmt->closeCursor();

        return $obj;
    }

    /**
     * Find object by primary key.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return ArchivoCalificacion|ArchivoCalificacion[]|mixed the result, formatted by the current formatter
     */
    protected function findPkComplex($key, $con)
    {
        // As the query uses a PK condition, no limit(1) is necessary.
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKey($key)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
    }

    /**
     * Find objects by primary key
     * <code>
     * $objs = $c->findPks(array(12, 56, 832), $con);
     * </code>
     * @param     array $keys Primary keys to use for the query
     * @param     PropelPDO $con an optional connection object
     *
     * @return PropelObjectCollection|ArchivoCalificacion[]|mixed the list of results, formatted by the current formatter
     */
    public function findPks($keys, $con = null)
    {
        if ($con === null) {
            $con = Propel::getConnection($this->getDbName(), Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKeys($keys)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->format($stmt);
    }

    /**
     * Filter the query by primary key
     *
     * @param     mixed $key Primary key to use for the query
     *
     * @return ArchivoCalificacionQuery The current query, for fluid interface
     */
    public function filterByPrimaryKey($key)
    {

        return $this->addUsingAlias(ArchivoCalificacionPeer::ID, $key, Criteria::EQUAL);
    }

    /**
     * Filter the query by a list of primary keys
     *
     * @param     array $keys The list of primary key to use for the query
     *
     * @return ArchivoCalificacionQuery The current query, for fluid interface
     */
    public function filterByPrimaryKeys($keys)
    {

        return $this->addUsingAlias(ArchivoCalificacionPeer::ID, $keys, Criteria::IN);
    }

    /**
     * Filter the query on the id column
     *
     * Example usage:
     * <code>
     * $query->filterById(1234); // WHERE id = 1234
     * $query->filterById(array(12, 34)); // WHERE id IN (12, 34)
     * $query->filterById(array('min' => 12)); // WHERE id > 12
     * </code>
     *
     * @param     mixed $id The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return ArchivoCalificacionQuery The current query, for fluid interface
     */
    public function filterById($id = null, $comparison = null)
    {
        if (is_array($id) && null === $comparison) {
            $comparison = Criteria::IN;
        }

        return $this->addUsingAlias(ArchivoCalificacionPeer::ID, $id, $comparison);
    }

    /**
     * Filter the query on the archivo_id column
     *
     * Example usage:
     * <code>
     * $query->filterByArchivoId(1234); // WHERE archivo_id = 1234
     * $query->filterByArchivoId(array(12, 34)); // WHERE archivo_id IN (12, 34)
     * $query->filterByArchivoId(array('min' => 12)); // WHERE archivo_id > 12
     * </code>
     *
     * @see       filterByArchivo()
     *
     * @param     mixed $archivoId The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return ArchivoCalificacionQuery The current query, for fluid interface
     */
    public function filterByArchivoId($archivoId = null, $comparison = null)
    {
        if (is_array($archivoId)) {
            $useMinMax = false;
            if (isset($archivoId['min'])) {
                $this->addUsingAlias(ArchivoCalificacionPeer::ARCHIVO_ID, $archivoId['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($archivoId['max'])) {
                $this->addUsingAlias(ArchivoCalificacionPeer::ARCHIVO_ID, $archivoId['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(ArchivoCalificacionPeer::ARCHIVO_ID, $archivoId, $comparison);
    }

    /**
     * Filter the query on the usuario_id column
     *
     * Example usage:
     * <code>
     * $query->filterByUsuarioId(1234); // WHERE usuario_id = 1234
     * $query->filterByUsuarioId(array(12, 34)); // WHERE usuario_id IN (12, 34)
     * $query->filterByUsuarioId(array('min' => 12)); // WHERE usuario_id > 12
     * </code>
     *
     * @see       filterByUsuario()
     *
     * @param     mixed $usuarioId The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return ArchivoCalificacionQuery The current query, for fluid interface
     */
    public function filterByUsuarioId($usuarioId = null, $comparison = null)
    {
        if (is_array($usuarioId)) {
            $useMinMax = false;
            if (isset($usuarioId['min'])) {
                $this->addUsingAlias(ArchivoCalificacionPeer::USUARIO_ID, $usuarioId['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($usuarioId['max'])) {
                $this->addUsingAlias(ArchivoCalificacionPeer::USUARIO_ID, $usuarioId['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(ArchivoCalificacionPeer::USUARIO_ID, $usuarioId, $comparison);
    }

    /**
     * Filter the query on the punteo column
     *
     * Example usage:
     * <code>
     * $query->filterByPunteo(1234); // WHERE punteo = 1234
     * $query->filterByPunteo(array(12, 34)); // WHERE punteo IN (12, 34)
     * $query->filterByPunteo(array('min' => 12)); // WHERE punteo > 12
     * </code>
     *
     * @param     mixed $punteo The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return ArchivoCalificacionQuery The current query, for fluid interface
     */
    public function filterByPunteo($punteo = null, $comparison = null)
    {
        if (is_array($punteo)) {
            $useMinMax = false;
            if (isset($punteo['min'])) {
                $this->addUsingAlias(ArchivoCalificacionPeer::PUNTEO, $punteo['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($punteo['max'])) {
                $this->addUsingAlias(ArchivoCalificacionPeer::PUNTEO, $punteo['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(ArchivoCalificacionPeer::PUNTEO, $punteo, $comparison);
    }

    /**
     * Filter the query by a related Archivo object
     *
     * @param   Archivo|PropelObjectCollection $archivo The related object(s) to use as filter
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return   ArchivoCalificacionQuery The current query, for fluid interface
     * @throws   PropelException - if the provided filter is invalid.
     */
    public function filterByArchivo($archivo, $comparison = null)
    {
        if ($archivo instanceof Archivo) {
            return $this
                ->addUsingAlias(ArchivoCalificacionPeer::ARCHIVO_ID, $archivo->getId(), $comparison);
        } elseif ($archivo instanceof PropelObjectCollection) {
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }

            return $this
                ->addUsingAlias(ArchivoCalificacionPeer::ARCHIVO_ID, $archivo->toKeyValue('PrimaryKey', 'Id'), $comparison);
        } else {
            throw new PropelException('filterByArchivo() only accepts arguments of type Archivo or PropelCollection');
        }
    }

    /**
     * Adds a JOIN clause to the query using the Archivo relation
     *
     * @param     string $relationAlias optional alias for the relation
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return ArchivoCalificacionQuery The current query, for fluid interface
     */
    public function joinArchivo($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
    {
        $tableMap = $this->getTableMap();
        $relationMap = $tableMap->getRelation('Archivo');

        // create a ModelJoin object for this join
        $join = new ModelJoin();
        $join->setJoinType($joinType);
        $join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
        if ($previousJoin = $this->getPreviousJoin()) {
            $join->setPreviousJoin($previousJoin);
        }

        // add the ModelJoin to the current object
        if ($relationAlias) {
            $this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
            $this->addJoinObject($join, $relationAlias);
        } else {
            $this->addJoinObject($join, 'Archivo');
        }

        return $this;
    }

    /**
     * Use the Archivo relation Archivo object
     *
     * @see       useQuery()
     *
     * @param     string $relationAlias optional alias for the relation,
     *                                   to be used as main alias in the secondary query
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return   ArchivoQuery A secondary query class using the current class as primary query
     */
    public function useArchivoQuery($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
    {
        return $this
            ->joinArchivo($relationAlias, $joinType)
            ->useQuery($relationAlias ? $relationAlias : 'Archivo', 'ArchivoQuery');
    }

    /**
     * Filter the query by a related Usuario object
     *
     * @param   Usuario|PropelObjectCollection $usuario The related object(s) to use as filter
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return   ArchivoCalificacionQuery The current query, for fluid interface
     * @throws   PropelException - if the provided filter is invalid.
     */
    public function filterByUsuario($usuario, $comparison = null)
    {
        if ($usuario instanceof Usuario) {
            return $this
                ->addUsingAlias(ArchivoCalificacionPeer::USUARIO_ID, $usuario->getId(), $comparison);
        } elseif ($usuario instanceof PropelObjectCollection) {
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }

            return $this
                ->addUsingAlias(ArchivoCalificacionPeer::USUARIO_ID, $usuario->toKeyValue('PrimaryKey', 'Id'), $comparison);
        } else {
            throw new PropelException('filterByUsuario() only accepts arguments of type Usuario or PropelCollection');
        }
    }

    /**
     * Adds a JOIN clause to the query using the Usuario relation
     *
     * @param     string $relationAlias optional alias for the relation
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return ArchivoCalificacionQuery The current query, for fluid interface
     */
    public function joinUsuario($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
    {
        $tableMap = $this->getTableMap();
        $relationMap = $tableMap->getRelation('Usuario');

        // create a ModelJoin object for this join
        $join = new ModelJoin();
        $join->setJoinType($joinType);
        $join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
        if ($previousJoin = $this->getPreviousJoin()) {
            $join->setPreviousJoin($previousJoin);
        }

        // add the ModelJoin to the current object
        if ($relationAlias) {
            $this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
            $this->addJoinObject($join, $relationAlias);
        } else {
            $this->addJoinObject($join, 'Usuario');
        }

        return $this;
    }

    /**
     * Use the Usuario relation Usuario object
     *
     * @see       useQuery()
     *
     * @param     string $relationAlias optional alias for the relation,
     *                                   to be used as main alias in the secondary query
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return   UsuarioQuery A secondary query class using the current class as primary query
     */
    public function useUsuarioQuery($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
    {
        return $this
            ->joinUsuario($relationAlias, $joinType)
            ->useQuery($relationAlias ? $relationAlias : 'Usuario', 'UsuarioQuery');
    }

    /**
     * Exclude object from result
     *
     * @param   ArchivoCalificacion $archivoCalificacion Object to remove from the list of results
     *
     * @return ArchivoCalificacionQuery The current query, for fluid interface
     */
    public function prune($archivoCalificacion = null)
    {
        if ($archivoCalificacion) {
            $this->addUsingAlias(ArchivoCalificacionPeer::ID, $archivoCalificacion->getId(), Criteria::NOT_EQUAL);
        }

        return $this;
    }

}
