<?php


/**
 * Base class that represents a row from the 'mensaje_cabecera' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * Sun Dec 11 15:55:58 2016
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseMensajeCabecera extends BaseObject implements Persistent
{
    /**
     * Peer class name
     */
    const PEER = 'MensajeCabeceraPeer';

    /**
     * The Peer class.
     * Instance provides a convenient way of calling static methods on a class
     * that calling code may not be able to identify.
     * @var        MensajeCabeceraPeer
     */
    protected static $peer;

    /**
     * The flag var to prevent infinit loop in deep copy
     * @var       boolean
     */
    protected $startCopy = false;

    /**
     * The value for the id field.
     * @var        int
     */
    protected $id;

    /**
     * The value for the usuario1 field.
     * @var        int
     */
    protected $usuario1;

    /**
     * The value for the usuario2 field.
     * @var        int
     */
    protected $usuario2;

    /**
     * The value for the created_at field.
     * @var        string
     */
    protected $created_at;

    /**
     * The value for the updated_at field.
     * @var        string
     */
    protected $updated_at;

    /**
     * @var        Usuario
     */
    protected $aUsuarioRelatedByUsuario1;

    /**
     * @var        Usuario
     */
    protected $aUsuarioRelatedByUsuario2;

    /**
     * @var        PropelObjectCollection|Mensaje[] Collection to store aggregation of Mensaje objects.
     */
    protected $collMensajes;
    protected $collMensajesPartial;

    /**
     * Flag to prevent endless save loop, if this object is referenced
     * by another object which falls in this transaction.
     * @var        boolean
     */
    protected $alreadyInSave = false;

    /**
     * Flag to prevent endless validation loop, if this object is referenced
     * by another object which falls in this transaction.
     * @var        boolean
     */
    protected $alreadyInValidation = false;

    /**
     * An array of objects scheduled for deletion.
     * @var		PropelObjectCollection
     */
    protected $mensajesScheduledForDeletion = null;

    /**
     * Get the [id] column value.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Get the [usuario1] column value.
     *
     * @return int
     */
    public function getUsuario1()
    {
        return $this->usuario1;
    }

    /**
     * Get the [usuario2] column value.
     *
     * @return int
     */
    public function getUsuario2()
    {
        return $this->usuario2;
    }

    /**
     * Get the [optionally formatted] temporal [created_at] column value.
     *
     *
     * @param string $format The date/time format string (either date()-style or strftime()-style).
     *				 If format is null, then the raw DateTime object will be returned.
     * @return mixed Formatted date/time value as string or DateTime object (if format is null), null if column is null, and 0 if column value is 0000-00-00 00:00:00
     * @throws PropelException - if unable to parse/validate the date/time value.
     */
    public function getCreatedAt($format = 'Y-m-d H:i:s')
    {
        if ($this->created_at === null) {
            return null;
        }

        if ($this->created_at === '0000-00-00 00:00:00') {
            // while technically this is not a default value of null,
            // this seems to be closest in meaning.
            return null;
        } else {
            try {
                $dt = new DateTime($this->created_at);
            } catch (Exception $x) {
                throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
            }
        }

        if ($format === null) {
            // Because propel.useDateTimeClass is true, we return a DateTime object.
            return $dt;
        } elseif (strpos($format, '%') !== false) {
            return strftime($format, $dt->format('U'));
        } else {
            return $dt->format($format);
        }
    }

    /**
     * Get the [optionally formatted] temporal [updated_at] column value.
     *
     *
     * @param string $format The date/time format string (either date()-style or strftime()-style).
     *				 If format is null, then the raw DateTime object will be returned.
     * @return mixed Formatted date/time value as string or DateTime object (if format is null), null if column is null, and 0 if column value is 0000-00-00 00:00:00
     * @throws PropelException - if unable to parse/validate the date/time value.
     */
    public function getUpdatedAt($format = 'Y-m-d H:i:s')
    {
        if ($this->updated_at === null) {
            return null;
        }

        if ($this->updated_at === '0000-00-00 00:00:00') {
            // while technically this is not a default value of null,
            // this seems to be closest in meaning.
            return null;
        } else {
            try {
                $dt = new DateTime($this->updated_at);
            } catch (Exception $x) {
                throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->updated_at, true), $x);
            }
        }

        if ($format === null) {
            // Because propel.useDateTimeClass is true, we return a DateTime object.
            return $dt;
        } elseif (strpos($format, '%') !== false) {
            return strftime($format, $dt->format('U'));
        } else {
            return $dt->format($format);
        }
    }

    /**
     * Set the value of [id] column.
     *
     * @param int $v new value
     * @return MensajeCabecera The current object (for fluent API support)
     */
    public function setId($v)
    {
        if ($v !== null) {
            $v = (int) $v;
        }

        if ($this->id !== $v) {
            $this->id = $v;
            $this->modifiedColumns[] = MensajeCabeceraPeer::ID;
        }


        return $this;
    } // setId()

    /**
     * Set the value of [usuario1] column.
     *
     * @param int $v new value
     * @return MensajeCabecera The current object (for fluent API support)
     */
    public function setUsuario1($v)
    {
        if ($v !== null) {
            $v = (int) $v;
        }

        if ($this->usuario1 !== $v) {
            $this->usuario1 = $v;
            $this->modifiedColumns[] = MensajeCabeceraPeer::USUARIO1;
        }

        if ($this->aUsuarioRelatedByUsuario1 !== null && $this->aUsuarioRelatedByUsuario1->getId() !== $v) {
            $this->aUsuarioRelatedByUsuario1 = null;
        }


        return $this;
    } // setUsuario1()

    /**
     * Set the value of [usuario2] column.
     *
     * @param int $v new value
     * @return MensajeCabecera The current object (for fluent API support)
     */
    public function setUsuario2($v)
    {
        if ($v !== null) {
            $v = (int) $v;
        }

        if ($this->usuario2 !== $v) {
            $this->usuario2 = $v;
            $this->modifiedColumns[] = MensajeCabeceraPeer::USUARIO2;
        }

        if ($this->aUsuarioRelatedByUsuario2 !== null && $this->aUsuarioRelatedByUsuario2->getId() !== $v) {
            $this->aUsuarioRelatedByUsuario2 = null;
        }


        return $this;
    } // setUsuario2()

    /**
     * Sets the value of [created_at] column to a normalized version of the date/time value specified.
     *
     * @param mixed $v string, integer (timestamp), or DateTime value.
     *               Empty strings are treated as null.
     * @return MensajeCabecera The current object (for fluent API support)
     */
    public function setCreatedAt($v)
    {
        $dt = PropelDateTime::newInstance($v, null, 'DateTime');
        if ($this->created_at !== null || $dt !== null) {
            $currentDateAsString = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
            $newDateAsString = $dt ? $dt->format('Y-m-d H:i:s') : null;
            if ($currentDateAsString !== $newDateAsString) {
                $this->created_at = $newDateAsString;
                $this->modifiedColumns[] = MensajeCabeceraPeer::CREATED_AT;
            }
        } // if either are not null


        return $this;
    } // setCreatedAt()

    /**
     * Sets the value of [updated_at] column to a normalized version of the date/time value specified.
     *
     * @param mixed $v string, integer (timestamp), or DateTime value.
     *               Empty strings are treated as null.
     * @return MensajeCabecera The current object (for fluent API support)
     */
    public function setUpdatedAt($v)
    {
        $dt = PropelDateTime::newInstance($v, null, 'DateTime');
        if ($this->updated_at !== null || $dt !== null) {
            $currentDateAsString = ($this->updated_at !== null && $tmpDt = new DateTime($this->updated_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
            $newDateAsString = $dt ? $dt->format('Y-m-d H:i:s') : null;
            if ($currentDateAsString !== $newDateAsString) {
                $this->updated_at = $newDateAsString;
                $this->modifiedColumns[] = MensajeCabeceraPeer::UPDATED_AT;
            }
        } // if either are not null


        return $this;
    } // setUpdatedAt()

    /**
     * Indicates whether the columns in this object are only set to default values.
     *
     * This method can be used in conjunction with isModified() to indicate whether an object is both
     * modified _and_ has some values set which are non-default.
     *
     * @return boolean Whether the columns in this object are only been set with default values.
     */
    public function hasOnlyDefaultValues()
    {
        // otherwise, everything was equal, so return true
        return true;
    } // hasOnlyDefaultValues()

    /**
     * Hydrates (populates) the object variables with values from the database resultset.
     *
     * An offset (0-based "start column") is specified so that objects can be hydrated
     * with a subset of the columns in the resultset rows.  This is needed, for example,
     * for results of JOIN queries where the resultset row includes columns from two or
     * more tables.
     *
     * @param array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
     * @param int $startcol 0-based offset column which indicates which restultset column to start with.
     * @param boolean $rehydrate Whether this object is being re-hydrated from the database.
     * @return int             next starting column
     * @throws PropelException - Any caught Exception will be rewrapped as a PropelException.
     */
    public function hydrate($row, $startcol = 0, $rehydrate = false)
    {
        try {

            $this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
            $this->usuario1 = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
            $this->usuario2 = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
            $this->created_at = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
            $this->updated_at = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
            $this->resetModified();

            $this->setNew(false);

            if ($rehydrate) {
                $this->ensureConsistency();
            }

            return $startcol + 5; // 5 = MensajeCabeceraPeer::NUM_HYDRATE_COLUMNS.

        } catch (Exception $e) {
            throw new PropelException("Error populating MensajeCabecera object", $e);
        }
    }

    /**
     * Checks and repairs the internal consistency of the object.
     *
     * This method is executed after an already-instantiated object is re-hydrated
     * from the database.  It exists to check any foreign keys to make sure that
     * the objects related to the current object are correct based on foreign key.
     *
     * You can override this method in the stub class, but you should always invoke
     * the base method from the overridden method (i.e. parent::ensureConsistency()),
     * in case your model changes.
     *
     * @throws PropelException
     */
    public function ensureConsistency()
    {

        if ($this->aUsuarioRelatedByUsuario1 !== null && $this->usuario1 !== $this->aUsuarioRelatedByUsuario1->getId()) {
            $this->aUsuarioRelatedByUsuario1 = null;
        }
        if ($this->aUsuarioRelatedByUsuario2 !== null && $this->usuario2 !== $this->aUsuarioRelatedByUsuario2->getId()) {
            $this->aUsuarioRelatedByUsuario2 = null;
        }
    } // ensureConsistency

    /**
     * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
     *
     * This will only work if the object has been saved and has a valid primary key set.
     *
     * @param boolean $deep (optional) Whether to also de-associated any related objects.
     * @param PropelPDO $con (optional) The PropelPDO connection to use.
     * @return void
     * @throws PropelException - if this object is deleted, unsaved or doesn't have pk match in db
     */
    public function reload($deep = false, PropelPDO $con = null)
    {
        if ($this->isDeleted()) {
            throw new PropelException("Cannot reload a deleted object.");
        }

        if ($this->isNew()) {
            throw new PropelException("Cannot reload an unsaved object.");
        }

        if ($con === null) {
            $con = Propel::getConnection(MensajeCabeceraPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }

        // We don't need to alter the object instance pool; we're just modifying this instance
        // already in the pool.

        $stmt = MensajeCabeceraPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
        $row = $stmt->fetch(PDO::FETCH_NUM);
        $stmt->closeCursor();
        if (!$row) {
            throw new PropelException('Cannot find matching row in the database to reload object values.');
        }
        $this->hydrate($row, 0, true); // rehydrate

        if ($deep) {  // also de-associate any related objects?

            $this->aUsuarioRelatedByUsuario1 = null;
            $this->aUsuarioRelatedByUsuario2 = null;
            $this->collMensajes = null;

        } // if (deep)
    }

    /**
     * Removes this object from datastore and sets delete attribute.
     *
     * @param PropelPDO $con
     * @return void
     * @throws PropelException
     * @throws Exception
     * @see        BaseObject::setDeleted()
     * @see        BaseObject::isDeleted()
     */
    public function delete(PropelPDO $con = null)
    {
        if ($this->isDeleted()) {
            throw new PropelException("This object has already been deleted.");
        }

        if ($con === null) {
            $con = Propel::getConnection(MensajeCabeceraPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
        }

        $con->beginTransaction();
        try {
            $deleteQuery = MensajeCabeceraQuery::create()
                ->filterByPrimaryKey($this->getPrimaryKey());
            $ret = $this->preDelete($con);
            // symfony_behaviors behavior
            foreach (sfMixer::getCallables('BaseMensajeCabecera:delete:pre') as $callable)
            {
              if (call_user_func($callable, $this, $con))
              {
                $con->commit();
                return;
              }
            }

            if ($ret) {
                $deleteQuery->delete($con);
                $this->postDelete($con);
                // symfony_behaviors behavior
                foreach (sfMixer::getCallables('BaseMensajeCabecera:delete:post') as $callable)
                {
                  call_user_func($callable, $this, $con);
                }

                $con->commit();
                $this->setDeleted(true);
            } else {
                $con->commit();
            }
        } catch (Exception $e) {
            $con->rollBack();
            throw $e;
        }
    }

    /**
     * Persists this object to the database.
     *
     * If the object is new, it inserts it; otherwise an update is performed.
     * All modified related objects will also be persisted in the doSave()
     * method.  This method wraps all precipitate database operations in a
     * single transaction.
     *
     * @param PropelPDO $con
     * @return int             The number of rows affected by this insert/update and any referring fk objects' save() operations.
     * @throws PropelException
     * @throws Exception
     * @see        doSave()
     */
    public function save(PropelPDO $con = null)
    {
        if ($this->isDeleted()) {
            throw new PropelException("You cannot save an object that has been deleted.");
        }

        if ($con === null) {
            $con = Propel::getConnection(MensajeCabeceraPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
        }

        $con->beginTransaction();
        $isInsert = $this->isNew();
        try {
            $ret = $this->preSave($con);
            // symfony_behaviors behavior
            foreach (sfMixer::getCallables('BaseMensajeCabecera:save:pre') as $callable)
            {
              if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
              {
                  $con->commit();
                return $affectedRows;
              }
            }

            // symfony_timestampable behavior
            if ($this->isModified() && !$this->isColumnModified(MensajeCabeceraPeer::UPDATED_AT))
            {
                $this->setUpdatedAt(time());
            }
            if ($isInsert) {
                $ret = $ret && $this->preInsert($con);
                // symfony_timestampable behavior
                if (!$this->isColumnModified(MensajeCabeceraPeer::CREATED_AT))
                {
                  $this->setCreatedAt(time());
                }

            } else {
                $ret = $ret && $this->preUpdate($con);
            }
            if ($ret) {
                $affectedRows = $this->doSave($con);
                if ($isInsert) {
                    $this->postInsert($con);
                } else {
                    $this->postUpdate($con);
                }
                $this->postSave($con);
                // symfony_behaviors behavior
                foreach (sfMixer::getCallables('BaseMensajeCabecera:save:post') as $callable)
                {
                  call_user_func($callable, $this, $con, $affectedRows);
                }

                MensajeCabeceraPeer::addInstanceToPool($this);
            } else {
                $affectedRows = 0;
            }
            $con->commit();

            return $affectedRows;
        } catch (Exception $e) {
            $con->rollBack();
            throw $e;
        }
    }

    /**
     * Performs the work of inserting or updating the row in the database.
     *
     * If the object is new, it inserts it; otherwise an update is performed.
     * All related objects are also updated in this method.
     *
     * @param PropelPDO $con
     * @return int             The number of rows affected by this insert/update and any referring fk objects' save() operations.
     * @throws PropelException
     * @see        save()
     */
    protected function doSave(PropelPDO $con)
    {
        $affectedRows = 0; // initialize var to track total num of affected rows
        if (!$this->alreadyInSave) {
            $this->alreadyInSave = true;

            // We call the save method on the following object(s) if they
            // were passed to this object by their coresponding set
            // method.  This object relates to these object(s) by a
            // foreign key reference.

            if ($this->aUsuarioRelatedByUsuario1 !== null) {
                if ($this->aUsuarioRelatedByUsuario1->isModified() || $this->aUsuarioRelatedByUsuario1->isNew()) {
                    $affectedRows += $this->aUsuarioRelatedByUsuario1->save($con);
                }
                $this->setUsuarioRelatedByUsuario1($this->aUsuarioRelatedByUsuario1);
            }

            if ($this->aUsuarioRelatedByUsuario2 !== null) {
                if ($this->aUsuarioRelatedByUsuario2->isModified() || $this->aUsuarioRelatedByUsuario2->isNew()) {
                    $affectedRows += $this->aUsuarioRelatedByUsuario2->save($con);
                }
                $this->setUsuarioRelatedByUsuario2($this->aUsuarioRelatedByUsuario2);
            }

            if ($this->isNew() || $this->isModified()) {
                // persist changes
                if ($this->isNew()) {
                    $this->doInsert($con);
                } else {
                    $this->doUpdate($con);
                }
                $affectedRows += 1;
                $this->resetModified();
            }

            if ($this->mensajesScheduledForDeletion !== null) {
                if (!$this->mensajesScheduledForDeletion->isEmpty()) {
                    foreach ($this->mensajesScheduledForDeletion as $mensaje) {
                        // need to save related object because we set the relation to null
                        $mensaje->save($con);
                    }
                    $this->mensajesScheduledForDeletion = null;
                }
            }

            if ($this->collMensajes !== null) {
                foreach ($this->collMensajes as $referrerFK) {
                    if (!$referrerFK->isDeleted()) {
                        $affectedRows += $referrerFK->save($con);
                    }
                }
            }

            $this->alreadyInSave = false;

        }

        return $affectedRows;
    } // doSave()

    /**
     * Insert the row in the database.
     *
     * @param PropelPDO $con
     *
     * @throws PropelException
     * @see        doSave()
     */
    protected function doInsert(PropelPDO $con)
    {
        $modifiedColumns = array();
        $index = 0;

        $this->modifiedColumns[] = MensajeCabeceraPeer::ID;
        if (null !== $this->id) {
            throw new PropelException('Cannot insert a value for auto-increment primary key (' . MensajeCabeceraPeer::ID . ')');
        }

         // check the columns in natural order for more readable SQL queries
        if ($this->isColumnModified(MensajeCabeceraPeer::ID)) {
            $modifiedColumns[':p' . $index++]  = '`ID`';
        }
        if ($this->isColumnModified(MensajeCabeceraPeer::USUARIO1)) {
            $modifiedColumns[':p' . $index++]  = '`USUARIO1`';
        }
        if ($this->isColumnModified(MensajeCabeceraPeer::USUARIO2)) {
            $modifiedColumns[':p' . $index++]  = '`USUARIO2`';
        }
        if ($this->isColumnModified(MensajeCabeceraPeer::CREATED_AT)) {
            $modifiedColumns[':p' . $index++]  = '`CREATED_AT`';
        }
        if ($this->isColumnModified(MensajeCabeceraPeer::UPDATED_AT)) {
            $modifiedColumns[':p' . $index++]  = '`UPDATED_AT`';
        }

        $sql = sprintf(
            'INSERT INTO `mensaje_cabecera` (%s) VALUES (%s)',
            implode(', ', $modifiedColumns),
            implode(', ', array_keys($modifiedColumns))
        );

        try {
            $stmt = $con->prepare($sql);
            foreach ($modifiedColumns as $identifier => $columnName) {
                switch ($columnName) {
                    case '`ID`':
                        $stmt->bindValue($identifier, $this->id, PDO::PARAM_INT);
                        break;
                    case '`USUARIO1`':
                        $stmt->bindValue($identifier, $this->usuario1, PDO::PARAM_INT);
                        break;
                    case '`USUARIO2`':
                        $stmt->bindValue($identifier, $this->usuario2, PDO::PARAM_INT);
                        break;
                    case '`CREATED_AT`':
                        $stmt->bindValue($identifier, $this->created_at, PDO::PARAM_STR);
                        break;
                    case '`UPDATED_AT`':
                        $stmt->bindValue($identifier, $this->updated_at, PDO::PARAM_STR);
                        break;
                }
            }
            $stmt->execute();
        } catch (Exception $e) {
            Propel::log($e->getMessage(), Propel::LOG_ERR);
            throw new PropelException(sprintf('Unable to execute INSERT statement [%s]', $sql), $e);
        }

        try {
            $pk = $con->lastInsertId();
        } catch (Exception $e) {
            throw new PropelException('Unable to get autoincrement id.', $e);
        }
        $this->setId($pk);

        $this->setNew(false);
    }

    /**
     * Update the row in the database.
     *
     * @param PropelPDO $con
     *
     * @see        doSave()
     */
    protected function doUpdate(PropelPDO $con)
    {
        $selectCriteria = $this->buildPkeyCriteria();
        $valuesCriteria = $this->buildCriteria();
        BasePeer::doUpdate($selectCriteria, $valuesCriteria, $con);
    }

    /**
     * Array of ValidationFailed objects.
     * @var        array ValidationFailed[]
     */
    protected $validationFailures = array();

    /**
     * Gets any ValidationFailed objects that resulted from last call to validate().
     *
     *
     * @return array ValidationFailed[]
     * @see        validate()
     */
    public function getValidationFailures()
    {
        return $this->validationFailures;
    }

    /**
     * Validates the objects modified field values and all objects related to this table.
     *
     * If $columns is either a column name or an array of column names
     * only those columns are validated.
     *
     * @param mixed $columns Column name or an array of column names.
     * @return boolean Whether all columns pass validation.
     * @see        doValidate()
     * @see        getValidationFailures()
     */
    public function validate($columns = null)
    {
        $res = $this->doValidate($columns);
        if ($res === true) {
            $this->validationFailures = array();

            return true;
        } else {
            $this->validationFailures = $res;

            return false;
        }
    }

    /**
     * This function performs the validation work for complex object models.
     *
     * In addition to checking the current object, all related objects will
     * also be validated.  If all pass then <code>true</code> is returned; otherwise
     * an aggreagated array of ValidationFailed objects will be returned.
     *
     * @param array $columns Array of column names to validate.
     * @return mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
     */
    protected function doValidate($columns = null)
    {
        if (!$this->alreadyInValidation) {
            $this->alreadyInValidation = true;
            $retval = null;

            $failureMap = array();


            // We call the validate method on the following object(s) if they
            // were passed to this object by their coresponding set
            // method.  This object relates to these object(s) by a
            // foreign key reference.

            if ($this->aUsuarioRelatedByUsuario1 !== null) {
                if (!$this->aUsuarioRelatedByUsuario1->validate($columns)) {
                    $failureMap = array_merge($failureMap, $this->aUsuarioRelatedByUsuario1->getValidationFailures());
                }
            }

            if ($this->aUsuarioRelatedByUsuario2 !== null) {
                if (!$this->aUsuarioRelatedByUsuario2->validate($columns)) {
                    $failureMap = array_merge($failureMap, $this->aUsuarioRelatedByUsuario2->getValidationFailures());
                }
            }


            if (($retval = MensajeCabeceraPeer::doValidate($this, $columns)) !== true) {
                $failureMap = array_merge($failureMap, $retval);
            }


                if ($this->collMensajes !== null) {
                    foreach ($this->collMensajes as $referrerFK) {
                        if (!$referrerFK->validate($columns)) {
                            $failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
                        }
                    }
                }


            $this->alreadyInValidation = false;
        }

        return (!empty($failureMap) ? $failureMap : true);
    }

    /**
     * Retrieves a field from the object by name passed in as a string.
     *
     * @param string $name name
     * @param string $type The type of fieldname the $name is of:
     *               one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
     *               BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
     *               Defaults to BasePeer::TYPE_PHPNAME
     * @return mixed Value of field.
     */
    public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
    {
        $pos = MensajeCabeceraPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
        $field = $this->getByPosition($pos);

        return $field;
    }

    /**
     * Retrieves a field from the object by Position as specified in the xml schema.
     * Zero-based.
     *
     * @param int $pos position in xml schema
     * @return mixed Value of field at $pos
     */
    public function getByPosition($pos)
    {
        switch ($pos) {
            case 0:
                return $this->getId();
                break;
            case 1:
                return $this->getUsuario1();
                break;
            case 2:
                return $this->getUsuario2();
                break;
            case 3:
                return $this->getCreatedAt();
                break;
            case 4:
                return $this->getUpdatedAt();
                break;
            default:
                return null;
                break;
        } // switch()
    }

    /**
     * Exports the object as an array.
     *
     * You can specify the key type of the array by passing one of the class
     * type constants.
     *
     * @param     string  $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
     *                    BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
     *                    Defaults to BasePeer::TYPE_PHPNAME.
     * @param     boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns. Defaults to true.
     * @param     array $alreadyDumpedObjects List of objects to skip to avoid recursion
     * @param     boolean $includeForeignObjects (optional) Whether to include hydrated related objects. Default to FALSE.
     *
     * @return array an associative array containing the field names (as keys) and field values
     */
    public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true, $alreadyDumpedObjects = array(), $includeForeignObjects = false)
    {
        if (isset($alreadyDumpedObjects['MensajeCabecera'][$this->getPrimaryKey()])) {
            return '*RECURSION*';
        }
        $alreadyDumpedObjects['MensajeCabecera'][$this->getPrimaryKey()] = true;
        $keys = MensajeCabeceraPeer::getFieldNames($keyType);
        $result = array(
            $keys[0] => $this->getId(),
            $keys[1] => $this->getUsuario1(),
            $keys[2] => $this->getUsuario2(),
            $keys[3] => $this->getCreatedAt(),
            $keys[4] => $this->getUpdatedAt(),
        );
        if ($includeForeignObjects) {
            if (null !== $this->aUsuarioRelatedByUsuario1) {
                $result['UsuarioRelatedByUsuario1'] = $this->aUsuarioRelatedByUsuario1->toArray($keyType, $includeLazyLoadColumns,  $alreadyDumpedObjects, true);
            }
            if (null !== $this->aUsuarioRelatedByUsuario2) {
                $result['UsuarioRelatedByUsuario2'] = $this->aUsuarioRelatedByUsuario2->toArray($keyType, $includeLazyLoadColumns,  $alreadyDumpedObjects, true);
            }
            if (null !== $this->collMensajes) {
                $result['Mensajes'] = $this->collMensajes->toArray(null, true, $keyType, $includeLazyLoadColumns, $alreadyDumpedObjects);
            }
        }

        return $result;
    }

    /**
     * Sets a field from the object by name passed in as a string.
     *
     * @param string $name peer name
     * @param mixed $value field value
     * @param string $type The type of fieldname the $name is of:
     *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
     *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
     *                     Defaults to BasePeer::TYPE_PHPNAME
     * @return void
     */
    public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
    {
        $pos = MensajeCabeceraPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);

        $this->setByPosition($pos, $value);
    }

    /**
     * Sets a field from the object by Position as specified in the xml schema.
     * Zero-based.
     *
     * @param int $pos position in xml schema
     * @param mixed $value field value
     * @return void
     */
    public function setByPosition($pos, $value)
    {
        switch ($pos) {
            case 0:
                $this->setId($value);
                break;
            case 1:
                $this->setUsuario1($value);
                break;
            case 2:
                $this->setUsuario2($value);
                break;
            case 3:
                $this->setCreatedAt($value);
                break;
            case 4:
                $this->setUpdatedAt($value);
                break;
        } // switch()
    }

    /**
     * Populates the object using an array.
     *
     * This is particularly useful when populating an object from one of the
     * request arrays (e.g. $_POST).  This method goes through the column
     * names, checking to see whether a matching key exists in populated
     * array. If so the setByName() method is called for that column.
     *
     * You can specify the key type of the array by additionally passing one
     * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
     * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
     * The default key type is the column's BasePeer::TYPE_PHPNAME
     *
     * @param array  $arr     An array to populate the object from.
     * @param string $keyType The type of keys the array uses.
     * @return void
     */
    public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
    {
        $keys = MensajeCabeceraPeer::getFieldNames($keyType);

        if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
        if (array_key_exists($keys[1], $arr)) $this->setUsuario1($arr[$keys[1]]);
        if (array_key_exists($keys[2], $arr)) $this->setUsuario2($arr[$keys[2]]);
        if (array_key_exists($keys[3], $arr)) $this->setCreatedAt($arr[$keys[3]]);
        if (array_key_exists($keys[4], $arr)) $this->setUpdatedAt($arr[$keys[4]]);
    }

    /**
     * Build a Criteria object containing the values of all modified columns in this object.
     *
     * @return Criteria The Criteria object containing all modified values.
     */
    public function buildCriteria()
    {
        $criteria = new Criteria(MensajeCabeceraPeer::DATABASE_NAME);

        if ($this->isColumnModified(MensajeCabeceraPeer::ID)) $criteria->add(MensajeCabeceraPeer::ID, $this->id);
        if ($this->isColumnModified(MensajeCabeceraPeer::USUARIO1)) $criteria->add(MensajeCabeceraPeer::USUARIO1, $this->usuario1);
        if ($this->isColumnModified(MensajeCabeceraPeer::USUARIO2)) $criteria->add(MensajeCabeceraPeer::USUARIO2, $this->usuario2);
        if ($this->isColumnModified(MensajeCabeceraPeer::CREATED_AT)) $criteria->add(MensajeCabeceraPeer::CREATED_AT, $this->created_at);
        if ($this->isColumnModified(MensajeCabeceraPeer::UPDATED_AT)) $criteria->add(MensajeCabeceraPeer::UPDATED_AT, $this->updated_at);

        return $criteria;
    }

    /**
     * Builds a Criteria object containing the primary key for this object.
     *
     * Unlike buildCriteria() this method includes the primary key values regardless
     * of whether or not they have been modified.
     *
     * @return Criteria The Criteria object containing value(s) for primary key(s).
     */
    public function buildPkeyCriteria()
    {
        $criteria = new Criteria(MensajeCabeceraPeer::DATABASE_NAME);
        $criteria->add(MensajeCabeceraPeer::ID, $this->id);

        return $criteria;
    }

    /**
     * Returns the primary key for this object (row).
     * @return int
     */
    public function getPrimaryKey()
    {
        return $this->getId();
    }

    /**
     * Generic method to set the primary key (id column).
     *
     * @param  int $key Primary key.
     * @return void
     */
    public function setPrimaryKey($key)
    {
        $this->setId($key);
    }

    /**
     * Returns true if the primary key for this object is null.
     * @return boolean
     */
    public function isPrimaryKeyNull()
    {

        return null === $this->getId();
    }

    /**
     * Sets contents of passed object to values from current object.
     *
     * If desired, this method can also make copies of all associated (fkey referrers)
     * objects.
     *
     * @param object $copyObj An object of MensajeCabecera (or compatible) type.
     * @param boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
     * @param boolean $makeNew Whether to reset autoincrement PKs and make the object new.
     * @throws PropelException
     */
    public function copyInto($copyObj, $deepCopy = false, $makeNew = true)
    {
        $copyObj->setUsuario1($this->getUsuario1());
        $copyObj->setUsuario2($this->getUsuario2());
        $copyObj->setCreatedAt($this->getCreatedAt());
        $copyObj->setUpdatedAt($this->getUpdatedAt());

        if ($deepCopy && !$this->startCopy) {
            // important: temporarily setNew(false) because this affects the behavior of
            // the getter/setter methods for fkey referrer objects.
            $copyObj->setNew(false);
            // store object hash to prevent cycle
            $this->startCopy = true;

            foreach ($this->getMensajes() as $relObj) {
                if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
                    $copyObj->addMensaje($relObj->copy($deepCopy));
                }
            }

            //unflag object copy
            $this->startCopy = false;
        } // if ($deepCopy)

        if ($makeNew) {
            $copyObj->setNew(true);
            $copyObj->setId(NULL); // this is a auto-increment column, so set to default value
        }
    }

    /**
     * Makes a copy of this object that will be inserted as a new row in table when saved.
     * It creates a new object filling in the simple attributes, but skipping any primary
     * keys that are defined for the table.
     *
     * If desired, this method can also make copies of all associated (fkey referrers)
     * objects.
     *
     * @param boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
     * @return MensajeCabecera Clone of current object.
     * @throws PropelException
     */
    public function copy($deepCopy = false)
    {
        // we use get_class(), because this might be a subclass
        $clazz = get_class($this);
        $copyObj = new $clazz();
        $this->copyInto($copyObj, $deepCopy);

        return $copyObj;
    }

    /**
     * Returns a peer instance associated with this om.
     *
     * Since Peer classes are not to have any instance attributes, this method returns the
     * same instance for all member of this class. The method could therefore
     * be static, but this would prevent one from overriding the behavior.
     *
     * @return MensajeCabeceraPeer
     */
    public function getPeer()
    {
        if (self::$peer === null) {
            self::$peer = new MensajeCabeceraPeer();
        }

        return self::$peer;
    }

    /**
     * Declares an association between this object and a Usuario object.
     *
     * @param             Usuario $v
     * @return MensajeCabecera The current object (for fluent API support)
     * @throws PropelException
     */
    public function setUsuarioRelatedByUsuario1(Usuario $v = null)
    {
        if ($v === null) {
            $this->setUsuario1(NULL);
        } else {
            $this->setUsuario1($v->getId());
        }

        $this->aUsuarioRelatedByUsuario1 = $v;

        // Add binding for other direction of this n:n relationship.
        // If this object has already been added to the Usuario object, it will not be re-added.
        if ($v !== null) {
            $v->addMensajeCabeceraRelatedByUsuario1($this);
        }


        return $this;
    }


    /**
     * Get the associated Usuario object
     *
     * @param PropelPDO $con Optional Connection object.
     * @return Usuario The associated Usuario object.
     * @throws PropelException
     */
    public function getUsuarioRelatedByUsuario1(PropelPDO $con = null)
    {
        if ($this->aUsuarioRelatedByUsuario1 === null && ($this->usuario1 !== null)) {
            $this->aUsuarioRelatedByUsuario1 = UsuarioQuery::create()->findPk($this->usuario1, $con);
            /* The following can be used additionally to
                guarantee the related object contains a reference
                to this object.  This level of coupling may, however, be
                undesirable since it could result in an only partially populated collection
                in the referenced object.
                $this->aUsuarioRelatedByUsuario1->addMensajeCabecerasRelatedByUsuario1($this);
             */
        }

        return $this->aUsuarioRelatedByUsuario1;
    }

    /**
     * Declares an association between this object and a Usuario object.
     *
     * @param             Usuario $v
     * @return MensajeCabecera The current object (for fluent API support)
     * @throws PropelException
     */
    public function setUsuarioRelatedByUsuario2(Usuario $v = null)
    {
        if ($v === null) {
            $this->setUsuario2(NULL);
        } else {
            $this->setUsuario2($v->getId());
        }

        $this->aUsuarioRelatedByUsuario2 = $v;

        // Add binding for other direction of this n:n relationship.
        // If this object has already been added to the Usuario object, it will not be re-added.
        if ($v !== null) {
            $v->addMensajeCabeceraRelatedByUsuario2($this);
        }


        return $this;
    }


    /**
     * Get the associated Usuario object
     *
     * @param PropelPDO $con Optional Connection object.
     * @return Usuario The associated Usuario object.
     * @throws PropelException
     */
    public function getUsuarioRelatedByUsuario2(PropelPDO $con = null)
    {
        if ($this->aUsuarioRelatedByUsuario2 === null && ($this->usuario2 !== null)) {
            $this->aUsuarioRelatedByUsuario2 = UsuarioQuery::create()->findPk($this->usuario2, $con);
            /* The following can be used additionally to
                guarantee the related object contains a reference
                to this object.  This level of coupling may, however, be
                undesirable since it could result in an only partially populated collection
                in the referenced object.
                $this->aUsuarioRelatedByUsuario2->addMensajeCabecerasRelatedByUsuario2($this);
             */
        }

        return $this->aUsuarioRelatedByUsuario2;
    }


    /**
     * Initializes a collection based on the name of a relation.
     * Avoids crafting an 'init[$relationName]s' method name
     * that wouldn't work when StandardEnglishPluralizer is used.
     *
     * @param string $relationName The name of the relation to initialize
     * @return void
     */
    public function initRelation($relationName)
    {
        if ('Mensaje' == $relationName) {
            $this->initMensajes();
        }
    }

    /**
     * Clears out the collMensajes collection
     *
     * This does not modify the database; however, it will remove any associated objects, causing
     * them to be refetched by subsequent calls to accessor method.
     *
     * @return void
     * @see        addMensajes()
     */
    public function clearMensajes()
    {
        $this->collMensajes = null; // important to set this to null since that means it is uninitialized
        $this->collMensajesPartial = null;
    }

    /**
     * reset is the collMensajes collection loaded partially
     *
     * @return void
     */
    public function resetPartialMensajes($v = true)
    {
        $this->collMensajesPartial = $v;
    }

    /**
     * Initializes the collMensajes collection.
     *
     * By default this just sets the collMensajes collection to an empty array (like clearcollMensajes());
     * however, you may wish to override this method in your stub class to provide setting appropriate
     * to your application -- for example, setting the initial array to the values stored in database.
     *
     * @param boolean $overrideExisting If set to true, the method call initializes
     *                                        the collection even if it is not empty
     *
     * @return void
     */
    public function initMensajes($overrideExisting = true)
    {
        if (null !== $this->collMensajes && !$overrideExisting) {
            return;
        }
        $this->collMensajes = new PropelObjectCollection();
        $this->collMensajes->setModel('Mensaje');
    }

    /**
     * Gets an array of Mensaje objects which contain a foreign key that references this object.
     *
     * If the $criteria is not null, it is used to always fetch the results from the database.
     * Otherwise the results are fetched from the database the first time, then cached.
     * Next time the same method is called without $criteria, the cached collection is returned.
     * If this MensajeCabecera is new, it will return
     * an empty collection or the current collection; the criteria is ignored on a new object.
     *
     * @param Criteria $criteria optional Criteria object to narrow the query
     * @param PropelPDO $con optional connection object
     * @return PropelObjectCollection|Mensaje[] List of Mensaje objects
     * @throws PropelException
     */
    public function getMensajes($criteria = null, PropelPDO $con = null)
    {
        $partial = $this->collMensajesPartial && !$this->isNew();
        if (null === $this->collMensajes || null !== $criteria  || $partial) {
            if ($this->isNew() && null === $this->collMensajes) {
                // return empty collection
                $this->initMensajes();
            } else {
                $collMensajes = MensajeQuery::create(null, $criteria)
                    ->filterByMensajeCabecera($this)
                    ->find($con);
                if (null !== $criteria) {
                    if (false !== $this->collMensajesPartial && count($collMensajes)) {
                      $this->initMensajes(false);

                      foreach($collMensajes as $obj) {
                        if (false == $this->collMensajes->contains($obj)) {
                          $this->collMensajes->append($obj);
                        }
                      }

                      $this->collMensajesPartial = true;
                    }

                    return $collMensajes;
                }

                if($partial && $this->collMensajes) {
                    foreach($this->collMensajes as $obj) {
                        if($obj->isNew()) {
                            $collMensajes[] = $obj;
                        }
                    }
                }

                $this->collMensajes = $collMensajes;
                $this->collMensajesPartial = false;
            }
        }

        return $this->collMensajes;
    }

    /**
     * Sets a collection of Mensaje objects related by a one-to-many relationship
     * to the current object.
     * It will also schedule objects for deletion based on a diff between old objects (aka persisted)
     * and new objects from the given Propel collection.
     *
     * @param PropelCollection $mensajes A Propel collection.
     * @param PropelPDO $con Optional connection object
     */
    public function setMensajes(PropelCollection $mensajes, PropelPDO $con = null)
    {
        $this->mensajesScheduledForDeletion = $this->getMensajes(new Criteria(), $con)->diff($mensajes);

        foreach ($this->mensajesScheduledForDeletion as $mensajeRemoved) {
            $mensajeRemoved->setMensajeCabecera(null);
        }

        $this->collMensajes = null;
        foreach ($mensajes as $mensaje) {
            $this->addMensaje($mensaje);
        }

        $this->collMensajes = $mensajes;
        $this->collMensajesPartial = false;
    }

    /**
     * Returns the number of related Mensaje objects.
     *
     * @param Criteria $criteria
     * @param boolean $distinct
     * @param PropelPDO $con
     * @return int             Count of related Mensaje objects.
     * @throws PropelException
     */
    public function countMensajes(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
    {
        $partial = $this->collMensajesPartial && !$this->isNew();
        if (null === $this->collMensajes || null !== $criteria || $partial) {
            if ($this->isNew() && null === $this->collMensajes) {
                return 0;
            } else {
                if($partial && !$criteria) {
                    return count($this->getMensajes());
                }
                $query = MensajeQuery::create(null, $criteria);
                if ($distinct) {
                    $query->distinct();
                }

                return $query
                    ->filterByMensajeCabecera($this)
                    ->count($con);
            }
        } else {
            return count($this->collMensajes);
        }
    }

    /**
     * Method called to associate a Mensaje object to this object
     * through the Mensaje foreign key attribute.
     *
     * @param    Mensaje $l Mensaje
     * @return MensajeCabecera The current object (for fluent API support)
     */
    public function addMensaje(Mensaje $l)
    {
        if ($this->collMensajes === null) {
            $this->initMensajes();
            $this->collMensajesPartial = true;
        }
        if (!$this->collMensajes->contains($l)) { // only add it if the **same** object is not already associated
            $this->doAddMensaje($l);
        }

        return $this;
    }

    /**
     * @param	Mensaje $mensaje The mensaje object to add.
     */
    protected function doAddMensaje($mensaje)
    {
        $this->collMensajes[]= $mensaje;
        $mensaje->setMensajeCabecera($this);
    }

    /**
     * @param	Mensaje $mensaje The mensaje object to remove.
     */
    public function removeMensaje($mensaje)
    {
        if ($this->getMensajes()->contains($mensaje)) {
            $this->collMensajes->remove($this->collMensajes->search($mensaje));
            if (null === $this->mensajesScheduledForDeletion) {
                $this->mensajesScheduledForDeletion = clone $this->collMensajes;
                $this->mensajesScheduledForDeletion->clear();
            }
            $this->mensajesScheduledForDeletion[]= $mensaje;
            $mensaje->setMensajeCabecera(null);
        }
    }


    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this MensajeCabecera is new, it will return
     * an empty collection; or if this MensajeCabecera has previously
     * been saved, it will retrieve related Mensajes from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in MensajeCabecera.
     *
     * @param Criteria $criteria optional Criteria object to narrow the query
     * @param PropelPDO $con optional connection object
     * @param string $join_behavior optional join type to use (defaults to Criteria::LEFT_JOIN)
     * @return PropelObjectCollection|Mensaje[] List of Mensaje objects
     */
    public function getMensajesJoinUsuarioRelatedByUsuarioEmisor($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
    {
        $query = MensajeQuery::create(null, $criteria);
        $query->joinWith('UsuarioRelatedByUsuarioEmisor', $join_behavior);

        return $this->getMensajes($query, $con);
    }


    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this MensajeCabecera is new, it will return
     * an empty collection; or if this MensajeCabecera has previously
     * been saved, it will retrieve related Mensajes from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in MensajeCabecera.
     *
     * @param Criteria $criteria optional Criteria object to narrow the query
     * @param PropelPDO $con optional connection object
     * @param string $join_behavior optional join type to use (defaults to Criteria::LEFT_JOIN)
     * @return PropelObjectCollection|Mensaje[] List of Mensaje objects
     */
    public function getMensajesJoinUsuarioRelatedByUsuarioReceptor($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
    {
        $query = MensajeQuery::create(null, $criteria);
        $query->joinWith('UsuarioRelatedByUsuarioReceptor', $join_behavior);

        return $this->getMensajes($query, $con);
    }

    /**
     * Clears the current object and sets all attributes to their default values
     */
    public function clear()
    {
        $this->id = null;
        $this->usuario1 = null;
        $this->usuario2 = null;
        $this->created_at = null;
        $this->updated_at = null;
        $this->alreadyInSave = false;
        $this->alreadyInValidation = false;
        $this->clearAllReferences();
        $this->resetModified();
        $this->setNew(true);
        $this->setDeleted(false);
    }

    /**
     * Resets all references to other model objects or collections of model objects.
     *
     * This method is a user-space workaround for PHP's inability to garbage collect
     * objects with circular references (even in PHP 5.3). This is currently necessary
     * when using Propel in certain daemon or large-volumne/high-memory operations.
     *
     * @param boolean $deep Whether to also clear the references on all referrer objects.
     */
    public function clearAllReferences($deep = false)
    {
        if ($deep) {
            if ($this->collMensajes) {
                foreach ($this->collMensajes as $o) {
                    $o->clearAllReferences($deep);
                }
            }
        } // if ($deep)

        if ($this->collMensajes instanceof PropelCollection) {
            $this->collMensajes->clearIterator();
        }
        $this->collMensajes = null;
        $this->aUsuarioRelatedByUsuario1 = null;
        $this->aUsuarioRelatedByUsuario2 = null;
    }

    /**
     * return the string representation of this object
     *
     * @return string
     */
    public function __toString()
    {
        return (string) $this->exportTo(MensajeCabeceraPeer::DEFAULT_STRING_FORMAT);
    }

    /**
     * return true is the object is in saving state
     *
     * @return boolean
     */
    public function isAlreadyInSave()
    {
        return $this->alreadyInSave;
    }

    /**
     * Catches calls to virtual methods
     */
    public function __call($name, $params)
    {

        // symfony_behaviors behavior
        if ($callable = sfMixer::getCallable('BaseMensajeCabecera:' . $name))
        {
          array_unshift($params, $this);
          return call_user_func_array($callable, $params);
        }


        return parent::__call($name, $params);
    }

}
