<?php


/**
 * Base class that represents a query for the 'correo' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * Thu Feb 23 06:33:16 2017
 *
 * @method CorreoQuery orderById($order = Criteria::ASC) Order by the id column
 * @method CorreoQuery orderByReceptor($order = Criteria::ASC) Order by the receptor column
 * @method CorreoQuery orderByContenido($order = Criteria::ASC) Order by the contenido column
 * @method CorreoQuery orderByAsunto($order = Criteria::ASC) Order by the asunto column
 * @method CorreoQuery orderByCreatedAt($order = Criteria::ASC) Order by the created_at column
 * @method CorreoQuery orderByUpdatedAt($order = Criteria::ASC) Order by the updated_at column
 * @method CorreoQuery orderByCreatedBy($order = Criteria::ASC) Order by the created_by column
 * @method CorreoQuery orderByUpdatedBy($order = Criteria::ASC) Order by the updated_by column
 * @method CorreoQuery orderByEnviado($order = Criteria::ASC) Order by the enviado column
 *
 * @method CorreoQuery groupById() Group by the id column
 * @method CorreoQuery groupByReceptor() Group by the receptor column
 * @method CorreoQuery groupByContenido() Group by the contenido column
 * @method CorreoQuery groupByAsunto() Group by the asunto column
 * @method CorreoQuery groupByCreatedAt() Group by the created_at column
 * @method CorreoQuery groupByUpdatedAt() Group by the updated_at column
 * @method CorreoQuery groupByCreatedBy() Group by the created_by column
 * @method CorreoQuery groupByUpdatedBy() Group by the updated_by column
 * @method CorreoQuery groupByEnviado() Group by the enviado column
 *
 * @method CorreoQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method CorreoQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method CorreoQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method Correo findOne(PropelPDO $con = null) Return the first Correo matching the query
 * @method Correo findOneOrCreate(PropelPDO $con = null) Return the first Correo matching the query, or a new Correo object populated from the query conditions when no match is found
 *
 * @method Correo findOneById(int $id) Return the first Correo filtered by the id column
 * @method Correo findOneByReceptor(string $receptor) Return the first Correo filtered by the receptor column
 * @method Correo findOneByContenido(string $contenido) Return the first Correo filtered by the contenido column
 * @method Correo findOneByAsunto(string $asunto) Return the first Correo filtered by the asunto column
 * @method Correo findOneByCreatedAt(string $created_at) Return the first Correo filtered by the created_at column
 * @method Correo findOneByUpdatedAt(string $updated_at) Return the first Correo filtered by the updated_at column
 * @method Correo findOneByCreatedBy(string $created_by) Return the first Correo filtered by the created_by column
 * @method Correo findOneByUpdatedBy(string $updated_by) Return the first Correo filtered by the updated_by column
 * @method Correo findOneByEnviado(boolean $enviado) Return the first Correo filtered by the enviado column
 *
 * @method array findById(int $id) Return Correo objects filtered by the id column
 * @method array findByReceptor(string $receptor) Return Correo objects filtered by the receptor column
 * @method array findByContenido(string $contenido) Return Correo objects filtered by the contenido column
 * @method array findByAsunto(string $asunto) Return Correo objects filtered by the asunto column
 * @method array findByCreatedAt(string $created_at) Return Correo objects filtered by the created_at column
 * @method array findByUpdatedAt(string $updated_at) Return Correo objects filtered by the updated_at column
 * @method array findByCreatedBy(string $created_by) Return Correo objects filtered by the created_by column
 * @method array findByUpdatedBy(string $updated_by) Return Correo objects filtered by the updated_by column
 * @method array findByEnviado(boolean $enviado) Return Correo objects filtered by the enviado column
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseCorreoQuery extends ModelCriteria
{
    /**
     * Initializes internal state of BaseCorreoQuery object.
     *
     * @param     string $dbName The dabase name
     * @param     string $modelName The phpName of a model, e.g. 'Book'
     * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
     */
    public function __construct($dbName = 'propel', $modelName = 'Correo', $modelAlias = null)
    {
        parent::__construct($dbName, $modelName, $modelAlias);
    }

    /**
     * Returns a new CorreoQuery object.
     *
     * @param     string $modelAlias The alias of a model in the query
     * @param     CorreoQuery|Criteria $criteria Optional Criteria to build the query from
     *
     * @return CorreoQuery
     */
    public static function create($modelAlias = null, $criteria = null)
    {
        if ($criteria instanceof CorreoQuery) {
            return $criteria;
        }
        $query = new CorreoQuery();
        if (null !== $modelAlias) {
            $query->setModelAlias($modelAlias);
        }
        if ($criteria instanceof Criteria) {
            $query->mergeWith($criteria);
        }

        return $query;
    }

    /**
     * Find object by primary key.
     * Propel uses the instance pool to skip the database if the object exists.
     * Go fast if the query is untouched.
     *
     * <code>
     * $obj  = $c->findPk(12, $con);
     * </code>
     *
     * @param mixed $key Primary key to use for the query
     * @param     PropelPDO $con an optional connection object
     *
     * @return   Correo|Correo[]|mixed the result, formatted by the current formatter
     */
    public function findPk($key, $con = null)
    {
        if ($key === null) {
            return null;
        }
        if ((null !== ($obj = CorreoPeer::getInstanceFromPool((string) $key))) && !$this->formatter) {
            // the object is alredy in the instance pool
            return $obj;
        }
        if ($con === null) {
            $con = Propel::getConnection(CorreoPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        if ($this->formatter || $this->modelAlias || $this->with || $this->select
         || $this->selectColumns || $this->asColumns || $this->selectModifiers
         || $this->map || $this->having || $this->joins) {
            return $this->findPkComplex($key, $con);
        } else {
            return $this->findPkSimple($key, $con);
        }
    }

    /**
     * Find object by primary key using raw SQL to go fast.
     * Bypass doSelect() and the object formatter by using generated code.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return   Correo A model object, or null if the key is not found
     * @throws   PropelException
     */
    protected function findPkSimple($key, $con)
    {
        $sql = 'SELECT `ID`, `RECEPTOR`, `CONTENIDO`, `ASUNTO`, `CREATED_AT`, `UPDATED_AT`, `CREATED_BY`, `UPDATED_BY`, `ENVIADO` FROM `correo` WHERE `ID` = :p0';
        try {
            $stmt = $con->prepare($sql);
            $stmt->bindValue(':p0', $key, PDO::PARAM_INT);
            $stmt->execute();
        } catch (Exception $e) {
            Propel::log($e->getMessage(), Propel::LOG_ERR);
            throw new PropelException(sprintf('Unable to execute SELECT statement [%s]', $sql), $e);
        }
        $obj = null;
        if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $obj = new Correo();
            $obj->hydrate($row);
            CorreoPeer::addInstanceToPool($obj, (string) $key);
        }
        $stmt->closeCursor();

        return $obj;
    }

    /**
     * Find object by primary key.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return Correo|Correo[]|mixed the result, formatted by the current formatter
     */
    protected function findPkComplex($key, $con)
    {
        // As the query uses a PK condition, no limit(1) is necessary.
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKey($key)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
    }

    /**
     * Find objects by primary key
     * <code>
     * $objs = $c->findPks(array(12, 56, 832), $con);
     * </code>
     * @param     array $keys Primary keys to use for the query
     * @param     PropelPDO $con an optional connection object
     *
     * @return PropelObjectCollection|Correo[]|mixed the list of results, formatted by the current formatter
     */
    public function findPks($keys, $con = null)
    {
        if ($con === null) {
            $con = Propel::getConnection($this->getDbName(), Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKeys($keys)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->format($stmt);
    }

    /**
     * Filter the query by primary key
     *
     * @param     mixed $key Primary key to use for the query
     *
     * @return CorreoQuery The current query, for fluid interface
     */
    public function filterByPrimaryKey($key)
    {

        return $this->addUsingAlias(CorreoPeer::ID, $key, Criteria::EQUAL);
    }

    /**
     * Filter the query by a list of primary keys
     *
     * @param     array $keys The list of primary key to use for the query
     *
     * @return CorreoQuery The current query, for fluid interface
     */
    public function filterByPrimaryKeys($keys)
    {

        return $this->addUsingAlias(CorreoPeer::ID, $keys, Criteria::IN);
    }

    /**
     * Filter the query on the id column
     *
     * Example usage:
     * <code>
     * $query->filterById(1234); // WHERE id = 1234
     * $query->filterById(array(12, 34)); // WHERE id IN (12, 34)
     * $query->filterById(array('min' => 12)); // WHERE id > 12
     * </code>
     *
     * @param     mixed $id The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return CorreoQuery The current query, for fluid interface
     */
    public function filterById($id = null, $comparison = null)
    {
        if (is_array($id) && null === $comparison) {
            $comparison = Criteria::IN;
        }

        return $this->addUsingAlias(CorreoPeer::ID, $id, $comparison);
    }

    /**
     * Filter the query on the receptor column
     *
     * Example usage:
     * <code>
     * $query->filterByReceptor('fooValue');   // WHERE receptor = 'fooValue'
     * $query->filterByReceptor('%fooValue%'); // WHERE receptor LIKE '%fooValue%'
     * </code>
     *
     * @param     string $receptor The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return CorreoQuery The current query, for fluid interface
     */
    public function filterByReceptor($receptor = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($receptor)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $receptor)) {
                $receptor = str_replace('*', '%', $receptor);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(CorreoPeer::RECEPTOR, $receptor, $comparison);
    }

    /**
     * Filter the query on the contenido column
     *
     * Example usage:
     * <code>
     * $query->filterByContenido('fooValue');   // WHERE contenido = 'fooValue'
     * $query->filterByContenido('%fooValue%'); // WHERE contenido LIKE '%fooValue%'
     * </code>
     *
     * @param     string $contenido The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return CorreoQuery The current query, for fluid interface
     */
    public function filterByContenido($contenido = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($contenido)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $contenido)) {
                $contenido = str_replace('*', '%', $contenido);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(CorreoPeer::CONTENIDO, $contenido, $comparison);
    }

    /**
     * Filter the query on the asunto column
     *
     * Example usage:
     * <code>
     * $query->filterByAsunto('fooValue');   // WHERE asunto = 'fooValue'
     * $query->filterByAsunto('%fooValue%'); // WHERE asunto LIKE '%fooValue%'
     * </code>
     *
     * @param     string $asunto The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return CorreoQuery The current query, for fluid interface
     */
    public function filterByAsunto($asunto = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($asunto)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $asunto)) {
                $asunto = str_replace('*', '%', $asunto);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(CorreoPeer::ASUNTO, $asunto, $comparison);
    }

    /**
     * Filter the query on the created_at column
     *
     * Example usage:
     * <code>
     * $query->filterByCreatedAt('2011-03-14'); // WHERE created_at = '2011-03-14'
     * $query->filterByCreatedAt('now'); // WHERE created_at = '2011-03-14'
     * $query->filterByCreatedAt(array('max' => 'yesterday')); // WHERE created_at > '2011-03-13'
     * </code>
     *
     * @param     mixed $createdAt The value to use as filter.
     *              Values can be integers (unix timestamps), DateTime objects, or strings.
     *              Empty strings are treated as NULL.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return CorreoQuery The current query, for fluid interface
     */
    public function filterByCreatedAt($createdAt = null, $comparison = null)
    {
        if (is_array($createdAt)) {
            $useMinMax = false;
            if (isset($createdAt['min'])) {
                $this->addUsingAlias(CorreoPeer::CREATED_AT, $createdAt['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($createdAt['max'])) {
                $this->addUsingAlias(CorreoPeer::CREATED_AT, $createdAt['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(CorreoPeer::CREATED_AT, $createdAt, $comparison);
    }

    /**
     * Filter the query on the updated_at column
     *
     * Example usage:
     * <code>
     * $query->filterByUpdatedAt('2011-03-14'); // WHERE updated_at = '2011-03-14'
     * $query->filterByUpdatedAt('now'); // WHERE updated_at = '2011-03-14'
     * $query->filterByUpdatedAt(array('max' => 'yesterday')); // WHERE updated_at > '2011-03-13'
     * </code>
     *
     * @param     mixed $updatedAt The value to use as filter.
     *              Values can be integers (unix timestamps), DateTime objects, or strings.
     *              Empty strings are treated as NULL.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return CorreoQuery The current query, for fluid interface
     */
    public function filterByUpdatedAt($updatedAt = null, $comparison = null)
    {
        if (is_array($updatedAt)) {
            $useMinMax = false;
            if (isset($updatedAt['min'])) {
                $this->addUsingAlias(CorreoPeer::UPDATED_AT, $updatedAt['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($updatedAt['max'])) {
                $this->addUsingAlias(CorreoPeer::UPDATED_AT, $updatedAt['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(CorreoPeer::UPDATED_AT, $updatedAt, $comparison);
    }

    /**
     * Filter the query on the created_by column
     *
     * Example usage:
     * <code>
     * $query->filterByCreatedBy('fooValue');   // WHERE created_by = 'fooValue'
     * $query->filterByCreatedBy('%fooValue%'); // WHERE created_by LIKE '%fooValue%'
     * </code>
     *
     * @param     string $createdBy The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return CorreoQuery The current query, for fluid interface
     */
    public function filterByCreatedBy($createdBy = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($createdBy)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $createdBy)) {
                $createdBy = str_replace('*', '%', $createdBy);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(CorreoPeer::CREATED_BY, $createdBy, $comparison);
    }

    /**
     * Filter the query on the updated_by column
     *
     * Example usage:
     * <code>
     * $query->filterByUpdatedBy('fooValue');   // WHERE updated_by = 'fooValue'
     * $query->filterByUpdatedBy('%fooValue%'); // WHERE updated_by LIKE '%fooValue%'
     * </code>
     *
     * @param     string $updatedBy The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return CorreoQuery The current query, for fluid interface
     */
    public function filterByUpdatedBy($updatedBy = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($updatedBy)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $updatedBy)) {
                $updatedBy = str_replace('*', '%', $updatedBy);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(CorreoPeer::UPDATED_BY, $updatedBy, $comparison);
    }

    /**
     * Filter the query on the enviado column
     *
     * Example usage:
     * <code>
     * $query->filterByEnviado(true); // WHERE enviado = true
     * $query->filterByEnviado('yes'); // WHERE enviado = true
     * </code>
     *
     * @param     boolean|string $enviado The value to use as filter.
     *              Non-boolean arguments are converted using the following rules:
     *                * 1, '1', 'true',  'on',  and 'yes' are converted to boolean true
     *                * 0, '0', 'false', 'off', and 'no'  are converted to boolean false
     *              Check on string values is case insensitive (so 'FaLsE' is seen as 'false').
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return CorreoQuery The current query, for fluid interface
     */
    public function filterByEnviado($enviado = null, $comparison = null)
    {
        if (is_string($enviado)) {
            $enviado = in_array(strtolower($enviado), array('false', 'off', '-', 'no', 'n', '0', '')) ? false : true;
        }

        return $this->addUsingAlias(CorreoPeer::ENVIADO, $enviado, $comparison);
    }

    /**
     * Exclude object from result
     *
     * @param   Correo $correo Object to remove from the list of results
     *
     * @return CorreoQuery The current query, for fluid interface
     */
    public function prune($correo = null)
    {
        if ($correo) {
            $this->addUsingAlias(CorreoPeer::ID, $correo->getId(), Criteria::NOT_EQUAL);
        }

        return $this;
    }

}
