<?php
// auto-generated by sfSecurityConfigHandler
// date: 2017/01/06 23:55:14
$this->security = array (
  'login' => 
  array (
    'is_secure' => 'false;',
  ),
  'registrar' => 
  array (
    'is_secure' => false,
  ),
  'validatoken' => 
  array (
    'is_secure' => false,
  ),
  'recuperaclave' => 
  array (
    'is_secure' => false,
  ),
  'recupera' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
