generator:
  class: sfPropelGenerator
  param:
    model_class:           universidad
    theme:                 admin15
    non_verbose_templates: true
    with_show:             false
    singular:              universidad
    plural:                universidads
    route_prefix:          universidad
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
          descripcion: 
              attributes:
                  class: form-control input-medium
          pais_id:
              attributes:
                  class: form-control select2me input-medium
      list:
          display:        [descripcion,pais]
          title:          Listado de Universidades
      filter:
          display:        [descripcion,pais_id]
      form:
          display:        [descripcion, pais_id]
      edit:
          title:          Editar Universidad (%%DESCRIPCION%%)
      new:
          title:          Nueva Universidad