<?php

/**
 * Skeleton subclass for representing a row from the 'archivo' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * Thu Nov 17 20:11:31 2016
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class Archivo extends BaseArchivo {

    public function postDelete(\PropelPDO $con = null) {
        rmdir($this->getUbicacion());
        parent::preDelete($con);
    }

    public function getTamanio() {
        $tamanio_kb = filesize($this->getUbicacion());
        $tamanio_kb = $tamanio_kb / 1000;
        if ($tamanio_kb >= 1024) {
            return number_format($tamanio_kb / 1024, 2) . 'MB';
        } else {
            return number_format($tamanio_kb, 2) . 'KB';
        }
    }

    public function getUbicacion() {
        return sfConfig::get('sf_upload_dir') . '/carga_archivos/' . $this->getNombreArchivoActual();
    }

    public function getExtension() {
        $nombre = explode('.', $this->getNombreArchivoOriginal());
        if (key_exists(1, $nombre)) {
            return strtolower($nombre[1]);
        } else {
            return strtolower($nombre[0]);
        }
    }

}
