<?php



/**
 * Skeleton subclass for performing query and update operations on the 'bitacora_acceso' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * Mon Nov 28 20:37:46 2016
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class BitacoraAccesoQuery extends BaseBitacoraAccesoQuery
{
}
