<?php



/**
 * Skeleton subclass for performing query and update operations on the 'categoria_materia' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * Wed Sep 28 20:24:01 2016
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class CategoriaMateriaPeer extends BaseCategoriaMateriaPeer
{
}
