<?php

/**
 * Skeleton subclass for performing query and update operations on the 'correo' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * Sat Sep 10 17:50:27 2016
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class CorreoPeer extends BaseCorreoPeer {

    static function EnvioCorreo() {
        $listado = CorreoQuery::create()->findByEnviado(false);
        $Configuracion = ConfiguracionCorreoQuery::create()->findOne();
        if ($Configuracion) {
            sfContext::getInstance()->getMailer()->getRealtimeTransport()->setHost($Configuracion->getHost());
            sfContext::getInstance()->getMailer()->getRealtimeTransport()->setEncryption($Configuracion->getEncriptacion());
            sfContext::getInstance()->getMailer()->getRealtimeTransport()->setport($Configuracion->getPuerto());
            sfContext::getInstance()->getMailer()->getRealtimeTransport()->setUsername($Configuracion->getUsuario());
            sfContext::getInstance()->getMailer()->getRealtimeTransport()->setPassword($Configuracion->getClave());
            foreach ($listado as $correo) {
                $message = sfContext::getInstance()->getMailer()->compose(
                        array('kennycornejo@gmail.com.com' => 'Kunes'), array($correo->getReceptor()), $correo->getAsunto(), $correo->getContenido()
                );
                $message->setContentType("text/html");
                $message->setBody($correo->getContenido(), "text/html");
                sfContext::getInstance()->getMailer()->send($message);
                $correo->setEnviado(true);
                $correo->save();
            }
        } else {
            echo 'NO SE TIENE DEFINIDA CONFIGURACION DE CORREO';
            error_log('NO SE TIENE DEFINIDA CONFIGURACION DE CORREO');
        }
    }

}
