<?php

/**
 * Skeleton subclass for representing a row from the 'formato_correo' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * Mon Sep 19 20:16:44 2016
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class FormatoCorreo extends BaseFormatoCorreo {

    public function getComodin() {
        $listado = array();
        $listado["%FECHA%"] = 'FECHA';
        $listado["%HORA%"] = 'HORA';
        switch ($this->getTipo()) {
            case 'Token':
                $listado["%LINK%"] = "LINK DE TOKEN";
                break;
            case 'Recuperacion':
                $listado["%LINK%"] = "LINK DE RECUPERACION";
                break;
        }
        return $listado;
    }

    public function getFormatoPlano($datos) {
        $texto = $this->getFormato();
        $texto = str_replace('%FECHA%', date('d/m/Y'), $texto);
        $texto = str_replace('%HORA%', date('H:i'), $texto);
        switch ($this->getTipo()) {
            case 'Token':
                $url = $datos['url'];
                $clave = $datos['token'];
                $texto = str_replace('%LINK%', '<a href="' . $url . 'seguridad/validaToken?token=' . $clave . '">LINK</a>', $texto);
                break;
            case 'Recuperacion':
                $url = $datos['url'];
                $clave = $datos['token'];
                $texto = str_replace('%LINK%', '<a href="' . $url . 'seguridad/recupera?token=' . $clave . '">LINK</a>', $texto);
                break;
        }
        return $texto;
    }

}
