<?php

/**
 * Skeleton subclass for representing a row from the 'mensaje_cabecera' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * Tue Sep 20 20:47:33 2016
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class MensajeCabecera extends BaseMensajeCabecera {

    public function getUltimoMensaje() {
        $Mensaje = MensajeQuery::create()
                ->filterByMensajeCabeceraId($this->getId())
                ->orderById('DESC')
                ->findOne();
        return $Mensaje;
    }

}
