<?php

/**
 * Skeleton subclass for representing a row from the 'mensaje' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * Sun Sep  4 00:13:42 2016
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class Mensaje extends BaseMensaje {

    function getUsuario() {
        $idUsuario = sfContext::getInstance()->getUser()->getAttribute('usuario', null, 'seguridad');
        $usuario = '';
        if ($this->getUsuarioEmisor() == $idUsuario) {
            $usuario = $this->getUsuarioRelatedByUsuarioReceptor()->getUsuario();
        } else {
            $usuario = $this->getUsuarioRelatedByUsuarioEmisor()->getUsuario();
        }
        return $usuario;
    }

    function getImagenUsuario() {
        $idUsuario = sfContext::getInstance()->getUser()->getAttribute('usuario', null, 'seguridad');
        $usuario = '';
        if ($this->getUsuarioEmisor() == $idUsuario) {
            $usuario = $this->getUsuarioRelatedByUsuarioReceptor()->getImagen();
        } else {
            $usuario = $this->getUsuarioRelatedByUsuarioEmisor()->getImagen();
        }
        return $usuario;
    }

    function save(\PropelPDO $con = null) {
        $idUsuario1 = $this->getUsuarioEmisor();
        $idUsuario2 = $this->getUsuarioReceptor();
        $comprobacion = MensajeCabeceraQuery::create()
                ->where("(usuario1 = $idUsuario1 and usuario2 = $idUsuario2) or (usuario2 = $idUsuario1 and usuario1 = $idUsuario2)")
                ->findOne();
        if (!$comprobacion) {
            $comprobacion = new MensajeCabecera();
            $comprobacion->setUsuario1($idUsuario1);
            $comprobacion->setUsuario2($idUsuario2);
            $comprobacion->save();
        }
        $this->setMensajeCabeceraId($comprobacion->getId());
        parent::save($con);
    }

}
