<?php



/**
 * Skeleton subclass for representing a row from the 'token_usuario' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * Sat Sep 10 17:52:59 2016
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class TokenUsuario extends BaseTokenUsuario
{
}
